-- MySQL Script generated by MySQL Workbench
-- 06/09/16 20:57:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `dui` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechaNac` DATE NOT NULL,
  PRIMARY KEY (`dui`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `idMunicipio` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  INDEX `fk_Municipio_Departamento1_idx` (`idDepartamento` ASC),
  CONSTRAINT `fk_Municipio_Departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Votante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Votante` (
  `idVotante` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `dui` INT NOT NULL,
  `idMunicipio` INT NOT NULL,
  PRIMARY KEY (`idVotante`),
  INDEX `fk_Votante_Usuario_idx` (`dui` ASC),
  INDEX `fk_Votante_Municipio1_idx` (`idMunicipio` ASC),
  CONSTRAINT `fk_Votante_Usuario`
    FOREIGN KEY (`dui`)
    REFERENCES `mydb`.`Usuario` (`dui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votante_Municipio1`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RepresentanteONU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RepresentanteONU` (
  `idRepresentanteONU` INT NOT NULL,
  `dui` INT NOT NULL,
  PRIMARY KEY (`idRepresentanteONU`),
  INDEX `fk_RepresentanteONU_Usuario1_idx` (`dui` ASC),
  CONSTRAINT `fk_RepresentanteONU_Usuario1`
    FOREIGN KEY (`dui`)
    REFERENCES `mydb`.`Usuario` (`dui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MiembroJuntaDirectiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MiembroJuntaDirectiva` (
  `idMiembroJuntaDirectiva` INT NOT NULL,
  `dui` INT NOT NULL,
  PRIMARY KEY (`idMiembroJuntaDirectiva`),
  INDEX `fk_MiembroJuntaDirectiva_Usuario1_idx` (`dui` ASC),
  CONSTRAINT `fk_MiembroJuntaDirectiva_Usuario1`
    FOREIGN KEY (`dui`)
    REFERENCES `mydb`.`Usuario` (`dui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PresidenteTSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PresidenteTSE` (
  `idPresidenteTSE` INT NOT NULL,
  `dui` INT NOT NULL,
  PRIMARY KEY (`idPresidenteTSE`),
  INDEX `fk_PresidenteTSE_Usuario1_idx` (`dui` ASC),
  CONSTRAINT `fk_PresidenteTSE_Usuario1`
    FOREIGN KEY (`dui`)
    REFERENCES `mydb`.`Usuario` (`dui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdministradorTotal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AdministradorTotal` (
  `idAdministradorTotal` INT NOT NULL,
  `dui` INT NOT NULL,
  PRIMARY KEY (`idAdministradorTotal`),
  INDEX `fk_AdministradorTotal_Usuario1_idx` (`dui` ASC),
  CONSTRAINT `fk_AdministradorTotal_Usuario1`
    FOREIGN KEY (`dui`)
    REFERENCES `mydb`.`Usuario` (`dui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RepresentanteTSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RepresentanteTSE` (
  `idRepresentanteTSE` INT NOT NULL,
  `dui` INT NOT NULL,
  PRIMARY KEY (`idRepresentanteTSE`),
  INDEX `fk_RepresentanteTSE_Usuario1_idx` (`dui` ASC),
  CONSTRAINT `fk_RepresentanteTSE_Usuario1`
    FOREIGN KEY (`dui`)
    REFERENCES `mydb`.`Usuario` (`dui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RepresentantePP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RepresentantePP` (
  `idRepresentantePP` INT NOT NULL,
  `dui` INT NOT NULL,
  PRIMARY KEY (`idRepresentantePP`),
  INDEX `fk_RepresentantePP_Usuario1_idx` (`dui` ASC),
  CONSTRAINT `fk_RepresentantePP_Usuario1`
    FOREIGN KEY (`dui`)
    REFERENCES `mydb`.`Usuario` (`dui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PartidoPolitico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PartidoPolitico` (
  `idPartido` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPartido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Candidato` (
  `idCandidato` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `idPartido` INT NOT NULL,
  PRIMARY KEY (`idCandidato`),
  INDEX `fk_Candidato_PartidoPolitico1_idx` (`idPartido` ASC),
  CONSTRAINT `fk_Candidato_PartidoPolitico1`
    FOREIGN KEY (`idPartido`)
    REFERENCES `mydb`.`PartidoPolitico` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voto` (
  `idVoto` INT NOT NULL,
  `idCandidato` INT NOT NULL,
  `idVotante` INT NOT NULL,
  PRIMARY KEY (`idVoto`),
  INDEX `fk_Voto_Candidato1_idx` (`idCandidato` ASC),
  INDEX `fk_Voto_Votante1_idx` (`idVotante` ASC),
  CONSTRAINT `fk_Voto_Candidato1`
    FOREIGN KEY (`idCandidato`)
    REFERENCES `mydb`.`Candidato` (`idCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voto_Votante1`
    FOREIGN KEY (`idVotante`)
    REFERENCES `mydb`.`Votante` (`idVotante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reporte` (
  `idReporte` INT NOT NULL,
  `idVoto` INT NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `fk_Reporte_Voto1_idx` (`idVoto` ASC),
  CONSTRAINT `fk_Reporte_Voto1`
    FOREIGN KEY (`idVoto`)
    REFERENCES `mydb`.`Voto` (`idVoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
